### ISSUE TITLE
Cannot read property 'model' of undefined

### ISSUE THREAD

**Issue by Arcrammer** [kennethklee/node-mongoose-fixtures#5]
I get this when I run the script. Why?

```
        var model = db.model(tableName);
                      ^

TypeError: Cannot read property 'model' of undefined
    at /Users/alexander/Sites/Savannah/node_modules/node-mongoose-fixtures/lib/index.js:25:23
    at /Users/alexander/Sites/Savannah/node_modules/async/lib/async.js:227:13
    at /Users/alexander/Sites/Savannah/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/Users/alexander/Sites/Savannah/node_modules/async/lib/async.js:32:24)
    at async.each (/Users/alexander/Sites/Savannah/node_modules/async/lib/async.js:110:9)
    at _asyncMap (/Users/alexander/Sites/Savannah/node_modules/async/lib/async.js:226:9)
    at Object.map (/Users/alexander/Sites/Savannah/node_modules/async/lib/async.js:204:23)
    at module.exports (/Users/alexander/Sites/Savannah/node_modules/node-mongoose-fixtures/lib/index.js:24:11)
    at Object.<anonymous> (/Users/alexander/Sites/Savannah/data/seeds.js:14:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
```

**Comment by Arcrammer** [comment]
`mongod` wasn't running /(-________-")
